import type { MeetingDetail } from "@/types/meeting";

export const productDesignReviewMeeting: MeetingDetail = {
  id: "product-design-review",
  title: "Product design review",
  date: "Saturday, September 26, 2026",
  time: "10:00 AM",
  duration: "46 min",
  durationSeconds: 2778,
  participants: [
    { name: "Maya Chen", initials: "MC", role: "Product Design", color: "bg-[#f18f62]" },
    { name: "Omar Haleem", initials: "OH", role: "Product", color: "bg-[#6b9bd2]" },
    { name: "Noah Williams", initials: "NW", role: "Engineering", color: "bg-[#9b7bd8]" },
    { name: "Leila Khan", initials: "LK", role: "Research", color: "bg-[#58b8ba]" },
    { name: "Sam Foster", initials: "SF", role: "Growth", color: "bg-[#cd7fae]" },
  ],
  waveform: [
    22, 35, 52, 30, 72, 46, 28, 64, 88, 40, 58, 32, 76, 48, 92, 54, 38, 66, 44, 82, 36, 62, 50, 74,
    30, 56, 86, 42, 68, 34, 78, 52, 94, 46, 60, 28, 72, 40, 84, 50, 64, 32, 70, 44, 90, 38, 58, 26,
  ],
  purpose:
    "Review the redesigned workspace navigation, resolve open interaction questions, and agree on the smallest launch-ready scope for the October beta.",
  takeaways: [
    "The new left rail tested better than the current top navigation, especially for returning users moving between meetings and highlights.",
    "First-time users still need clearer labels and a visible path back to their recent meetings after opening a transcript.",
    "The team can ship the core navigation without delaying the beta, provided keyboard states and mobile behavior are included in the next handoff.",
  ],
  decisions: [
    "Use the collapsible left rail as the primary desktop navigation pattern.",
    "Keep Overview, Meetings, Highlights, and Search in the first release; defer custom folders.",
    "Run one focused usability pass before development is marked release-ready.",
  ],
  actionItems: [
    {
      id: "action-1",
      task: "Update the navigation prototype with persistent labels and keyboard focus states.",
      owner: "Maya Chen",
      ownerInitials: "MC",
      ownerColor: "bg-[#f18f62]",
      deadline: "Sep 29",
      timestamp: "12:18",
      timestampSeconds: 738,
    },
    {
      id: "action-2",
      task: "Confirm the animation and collapsed-rail implementation estimate.",
      owner: "Noah Williams",
      ownerInitials: "NW",
      ownerColor: "bg-[#9b7bd8]",
      deadline: "Sep 30",
      timestamp: "24:42",
      timestampSeconds: 1482,
    },
    {
      id: "action-3",
      task: "Schedule five usability sessions using the updated prototype.",
      owner: "Leila Khan",
      ownerInitials: "LK",
      ownerColor: "bg-[#58b8ba]",
      deadline: "Oct 02",
      timestamp: "31:06",
      timestampSeconds: 1866,
    },
    {
      id: "action-4",
      task: "Rewrite the beta release brief around the three core workflows.",
      owner: "Omar Haleem",
      ownerInitials: "OH",
      ownerColor: "bg-[#6b9bd2]",
      deadline: "Oct 03",
      timestamp: "41:27",
      timestampSeconds: 2487,
    },
  ],
  highlights: [
    {
      id: "highlight-1",
      label: "Customer insight",
      title: "Labels remove hesitation",
      detail: "Participants completed repeat navigation tasks faster when the rail kept short text labels visible.",
      timestamp: "08:34",
      timestampSeconds: 514,
    },
    {
      id: "highlight-2",
      label: "Decision",
      title: "Three workflows for beta",
      detail: "The beta will focus on finding a meeting, reviewing its recap, and returning to highlights.",
      timestamp: "22:15",
      timestampSeconds: 1335,
    },
    {
      id: "highlight-3",
      label: "Design direction",
      title: "Motion should explain state",
      detail: "Collapse and floating transitions should clarify where navigation moved instead of feeling decorative.",
      timestamp: "37:48",
      timestampSeconds: 2268,
    },
  ],
  transcript: [
    {
      id: "segment-1",
      speaker: "Omar Haleem",
      speakerInitials: "OH",
      speakerColor: "bg-[#6b9bd2]",
      timestamp: "00:00",
      timestampSeconds: 0,
      text: "Thanks, everyone. The goal today is to leave with one navigation direction and a launch scope the team is comfortable committing to.",
    },
    {
      id: "segment-2",
      speaker: "Maya Chen",
      speakerInitials: "MC",
      speakerColor: "bg-[#f18f62]",
      timestamp: "03:21",
      timestampSeconds: 201,
      text: "I brought the two variants from last week. The first keeps the labels visible, while the second prioritizes a compact icon rail and expands on intent.",
    },
    {
      id: "segment-3",
      speaker: "Leila Khan",
      speakerInitials: "LK",
      speakerColor: "bg-[#58b8ba]",
      timestamp: "08:34",
      timestampSeconds: 514,
      text: "In the sessions, returning users understood both versions. Newer users hesitated on the icon-only rail, but the short labels removed that hesitation almost immediately.",
    },
    {
      id: "segment-4",
      speaker: "Noah Williams",
      speakerInitials: "NW",
      speakerColor: "bg-[#9b7bd8]",
      timestamp: "12:18",
      timestampSeconds: 738,
      text: "Persistent labels are straightforward. I would like the handoff to include focus states and the exact collapse behavior so we do not invent those during implementation.",
    },
    {
      id: "segment-5",
      speaker: "Maya Chen",
      speakerInitials: "MC",
      speakerColor: "bg-[#f18f62]",
      timestamp: "18:42",
      timestampSeconds: 1122,
      text: "That works. I also want the motion to explain where the navigation went. The floating control should feel like the same object, not a separate menu appearing from nowhere.",
    },
    {
      id: "segment-6",
      speaker: "Omar Haleem",
      speakerInitials: "OH",
      speakerColor: "bg-[#6b9bd2]",
      timestamp: "22:15",
      timestampSeconds: 1335,
      text: "For beta, let us keep the promise simple: find a meeting, understand what happened, and get back to the moments that matter. Custom folders can follow later.",
    },
    {
      id: "segment-7",
      speaker: "Sam Foster",
      speakerInitials: "SF",
      speakerColor: "bg-[#cd7fae]",
      timestamp: "29:50",
      timestampSeconds: 1790,
      text: "That gives us a much cleaner story. It also means the release screenshots can focus on outcomes instead of explaining configuration.",
    },
    {
      id: "segment-8",
      speaker: "Leila Khan",
      speakerInitials: "LK",
      speakerColor: "bg-[#58b8ba]",
      timestamp: "31:06",
      timestampSeconds: 1866,
      text: "I can run five focused sessions once the prototype is updated. We should know within two days whether the remaining labels are clear enough.",
    },
    {
      id: "segment-9",
      speaker: "Noah Williams",
      speakerInitials: "NW",
      speakerColor: "bg-[#9b7bd8]",
      timestamp: "37:48",
      timestampSeconds: 2268,
      text: "From engineering, the rail is safe for the beta. The drag interaction is additive, so it will not block the standard navigation behavior.",
    },
    {
      id: "segment-10",
      speaker: "Omar Haleem",
      speakerInitials: "OH",
      speakerColor: "bg-[#6b9bd2]",
      timestamp: "41:27",
      timestampSeconds: 2487,
      text: "Great. We have the direction, owners, and a validation step. I will update the release brief and bring the final scope back on Friday.",
    },
  ],
};
